[build]
  command = "echo skip"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/pix/create"
  to = "/.netlify/functions/pix-create"
  status = 200
  force = true

[[redirects]]
  from = "/api/pix/status/:id"
  to = "/.netlify/functions/pix-status?id=:id"
  status = 200
  force = true

[[redirects]]
  from = "/api/session"
  to = "/.netlify/functions/session"
  status = 200
  force = true
